extend type Query {
    reply(id: ID!): Reply
    blog(id: ID!): Blog
}

type Blog {
    id: String
    title: String
    content: String
}

type Reply {
    id: String
    blogParentId: String
    replyParentId: String
    content: String
}