#-----------------[ READING OAUTH ]-----------------#

extend type Query {
    oauth: OAuth
}

type OAuth {
    discord: Discord_Oauth
}

type Discord_Oauth {
    client_id: String
    client_secret: String       
    redirect_uri: String
    scopes: [String]
    url: String
}

#----------------------[ END ]----------------------#


#-----------------[ WRITING OAUTH ]-----------------#

extend type Mutation {
    oauth: OAuth_Mutation
}

type OAuth_Mutation {
    discord(
        code: String!,
        otp: String 
    ): User
}
#----------------------[ END ]----------------------#
