extend type Query {
    addon(id: String!): Addon      
    addons: [Addon]
}

type Addon {
    name: String
    id: String
    version: String
    author: String
    author_email: String
    types: [String]
    update: Addon_Update
}

type Addon_Update {
    update_url: String
    version_url: String
    changelog_url: String
}