extend type Query {
    role(id: String!): Role,
    roles: [Role_Object]
}

type Role  {
    name: String
    color: String
    permissions: [String]
    users: [String]
}

type Role_Object {
    id: String
    precedence: Int
}