extend type Query {
    role(id: String!): Role,
    roles: [Role_id]
}

type Role  {
    name: String
    color: String
    permissions: [String]
    users: [String]
}

type Role_id { 
    id: String
}